plugins {
	id "java-library"
}

group = "com.eatcloud"
version = "0.0.1-SNAPSHOT"

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}
repositories {
	mavenCentral()
}

dependencies {
	api(platform("org.springframework.boot:spring-boot-dependencies:3.5.3"))

	api("org.springframework.data:spring-data-jpa")

	compileOnly("org.springframework.boot:spring-boot-autoconfigure")
	compileOnly("org.springframework.boot:spring-boot-starter-web")

	implementation("org.springframework.security:spring-security-core")

	compileOnly("jakarta.persistence:jakarta.persistence-api")

	api("org.springframework.boot:spring-boot-starter-web")
}

tasks.matching { it.name == "bootJar" }.configureEach { enabled = false }
tasks.named("jar").configure {
	enabled = true
} // 라이브러리 JAR
