
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS postgis;


INSERT INTO p_stores (
    store_id, application_id, manager_id,
    store_name, store_address, phone_number,
    store_category_id, min_cost, description, store_lat, store_lon,
    open_status, open_time, close_time, location,
    rating_sum, rating_count, avg_rating,
    created_at, created_by, updated_at, updated_by
)
VALUES
    (gen_random_uuid(), gen_random_uuid(), gen_random_uuid(),
     '길동네 한식당', '서울 종로구 1번지', '02-111-2222',
     1, 10000, '정통 한식 전문점입니다.', 37.5725, 126.9769,
     TRUE, '10:00', '22:00',
     ST_SetSRID(ST_MakePoint(126.9769, 37.5725), 4326)::geography,
     0, 0, 0,
     now(), 'system', now(), 'system'),
    (gen_random_uuid(), gen_random_uuid(), gen_random_uuid(),
     '철수네 분식', '서울 마포구 2번지', '02-333-4444',
     2, 8000, '분식 전문점, 떡볶이/순대/튀김', 37.5555, 126.9369,
     TRUE, '09:00', '21:00',
     ST_SetSRID(ST_MakePoint(126.9369, 37.5555), 4326)::geography,
     0, 0, 0,
     now(), 'system', now(), 'system'),
    (gen_random_uuid(), gen_random_uuid(), gen_random_uuid(),
     '마포 양식당', '서울 마포구 10번지', '02-888-9999',
     4, 15000, '파스타와 스테이크 전문점', 37.5560, 126.9400,
     FALSE, '11:00', '23:00',
     ST_SetSRID(ST_MakePoint(126.9400, 37.5560), 4326)::geography,
     0, 0, 0,
     now(), 'system', now(), 'system'),
    (gen_random_uuid(), gen_random_uuid(), gen_random_uuid(),
     '맛있는 치킨', '서울 강남구 3번지', '02-555-6666',
     3, 15000, '치킨 전문점, 다양한 치킨 메뉴', 37.5000, 127.0000,
     TRUE, '11:00', '24:00',
     ST_SetSRID(ST_MakePoint(127.0000, 37.5000), 4326)::geography,
     0, 0, 0,
     now(), 'system', now(), 'system'),
    (gen_random_uuid(), gen_random_uuid(), gen_random_uuid(),
     '버거 하우스', '서울 서초구 4번지', '02-777-8888',
     5, 12000, '햄버거 전문점, 다양한 버거 메뉴', 37.4800, 127.0200,
     TRUE, '10:00', '23:00',
     ST_SetSRID(ST_MakePoint(127.0200, 37.4800), 4326)::geography,
     0, 0, 0,
     now(), 'system', now(), 'system'),
    (gen_random_uuid(), gen_random_uuid(), gen_random_uuid(),
     '스시 마스터', '서울 강남구 5번지', '02-999-0000',
     6, 25000, '정통 일본 스시 전문점', 37.5200, 127.0300,
     TRUE, '11:30', '22:00',
     ST_SetSRID(ST_MakePoint(127.0300, 37.5200), 4326)::geography,
     0, 0, 0,
     now(), 'system', now(), 'system'),
    (gen_random_uuid(), gen_random_uuid(), gen_random_uuid(),
     '중국집', '서울 서초구 6번지', '02-111-3333',
     7, 12000, '정통 중국 요리 전문점', 37.4900, 127.0100,
     TRUE, '11:00', '22:30',
     ST_SetSRID(ST_MakePoint(127.0100, 37.4900), 4326)::geography,
     0, 0, 0,
     now(), 'system', now(), 'system'),
    (gen_random_uuid(), gen_random_uuid(), gen_random_uuid(),
     '커피 로스터', '서울 마포구 7번지', '02-444-5555',
     8, 5000, '스페셜티 커피 전문점', 37.5600, 126.9300,
     TRUE, '08:00', '20:00',
     ST_SetSRID(ST_MakePoint(126.9300, 37.5600), 4326)::geography,
     0, 0, 0,
     now(), 'system', now(), 'system'),
    (gen_random_uuid(), gen_random_uuid(), gen_random_uuid(),
     '디저트 카페', '서울 강남구 8번지', '02-666-7777',
     9, 8000, '수제 디저트 전문 카페', 37.5100, 127.0400,
     TRUE, '10:00', '21:00',
     ST_SetSRID(ST_MakePoint(127.0400, 37.5100), 4326)::geography,
     0, 0, 0,
     now(), 'system', now(), 'system'),
    (gen_random_uuid(), gen_random_uuid(), gen_random_uuid(),
     '고기집', '서울 종로구 9번지', '02-222-3333',
     1, 20000, '프리미엄 고기 전문점', 37.5800, 126.9700,
     TRUE, '17:00', '23:00',
     ST_SetSRID(ST_MakePoint(126.9700, 37.5800), 4326)::geography,
     0, 0, 0,
     now(), 'system', now(), 'system');

INSERT INTO p_menus (
    menu_id, store_id, menu_num, menu_name, menu_category_code,
    price, description, is_available, image_url,
    is_unlimited, stock_quantity,
    created_at, created_by, updated_at, updated_by
)
VALUES
    (gen_random_uuid(),
     (SELECT store_id FROM p_stores WHERE store_name='길동네 한식당'),
     1, '비빔밥', 'BIBIMBAP', 9000, '신선한 야채와 고추장 비빔밥', TRUE, NULL,
     FALSE, 50,
     now(),'system',now(),'system'),
    (gen_random_uuid(),
     (SELECT store_id FROM p_stores WHERE store_name='길동네 한식당'),
     2, '김치찌개', 'JJIGAE', 8000, '얼큰한 김치찌개', TRUE, NULL,
     FALSE, 40,
     now(),'system',now(),'system'),
    (gen_random_uuid(),
     (SELECT store_id FROM p_stores WHERE store_name='길동네 한식당'),
     3, '불고기', 'BULGOGI', 12000, '달콤한 불고기', TRUE, NULL,
     FALSE, 30,
     now(),'system',now(),'system'),
    (gen_random_uuid(),
     (SELECT store_id FROM p_stores WHERE store_name='길동네 한식당'),
     4, '된장찌개', 'JJIGAE', 7000, '구수한 된장찌개', TRUE, NULL,
     FALSE, 45,
     now(),'system',now(),'system'),
    (gen_random_uuid(),
     (SELECT store_id FROM p_stores WHERE store_name='길동네 한식당'),
     5, '제육볶음', 'BOKKEUM', 11000, '매콤달콤한 제육볶음', TRUE, NULL,
     FALSE, 35,
     now(),'system',now(),'system'),
    (gen_random_uuid(),
     (SELECT store_id FROM p_stores WHERE store_name='철수네 분식'),
     1, '떡볶이', 'TTEOKBOKKI', 6000, '매콤달콤한 떡볶이', TRUE, NULL,
     FALSE, 100,
     now(),'system',now(),'system'),
    (gen_random_uuid(),
     (SELECT store_id FROM p_stores WHERE store_name='철수네 분식'),
     2, '김밥', 'GIMBAP', 4000, '정통 김밥', TRUE, NULL,
     TRUE, 0,
     now(),'system',now(),'system'),
    (gen_random_uuid(),
     (SELECT store_id FROM p_stores WHERE store_name='철수네 분식'),
     3, '라면', 'RAMEN', 5000, '얼큰한 라면', TRUE, NULL,
     FALSE, 80,
     now(),'system',now(),'system'),
    (gen_random_uuid(),
     (SELECT store_id FROM p_stores WHERE store_name='철수네 분식'),
     4, '순대', 'SUNDAE', 7000, '정통 순대', TRUE, NULL,
     FALSE, 60,
     now(),'system',now(),'system'),
    (gen_random_uuid(),
     (SELECT store_id FROM p_stores WHERE store_name='철수네 분식'),
     5, '튀김', 'TWIGIM', 8000, '바삭한 튀김 모듬', TRUE, NULL,
     FALSE, 70,
     now(),'system',now(),'system'),
    (gen_random_uuid(),
     (SELECT store_id FROM p_stores WHERE store_name='마포 양식당'),
     1, '스파게티', 'PASTA', 12000, '토마토 소스 스파게티', TRUE, NULL,
     FALSE, 30,
     now(),'system',now(),'system'),
    (gen_random_uuid(),
     (SELECT store_id FROM p_stores WHERE store_name='마포 양식당'),
     2, '까르보나라', 'PASTA', 14000, '크림 소스 까르보나라', TRUE, NULL,
     FALSE, 25,
     now(),'system',now(),'system'),
    (gen_random_uuid(),
     (SELECT store_id FROM p_stores WHERE store_name='마포 양식당'),
     3, '스테이크', 'STEAK', 25000, '프리미엄 스테이크', TRUE, NULL,
     FALSE, 20,
     now(),'system',now(),'system'),
    (gen_random_uuid(),
     (SELECT store_id FROM p_stores WHERE store_name='마포 양식당'),
     4, '피자', 'PIZZA', 18000, '정통 이탈리안 피자', TRUE, NULL,
     FALSE, 15,
     now(),'system',now(),'system'),
    (gen_random_uuid(),
     (SELECT store_id FROM p_stores WHERE store_name='마포 양식당'),
     5, '샐러드', 'SALAD', 9000, '신선한 그린샐러드', TRUE, NULL,
     FALSE, 40,
     now(),'system',now(),'system'),
    (gen_random_uuid(),
     (SELECT store_id FROM p_stores WHERE store_name='맛있는 치킨'),
     1, '후라이드 치킨', 'CHICKEN', 18000, '바삭한 후라이드 치킨', TRUE, NULL,
     FALSE, 25,
     now(),'system',now(),'system'),
    (gen_random_uuid(),
     (SELECT store_id FROM p_stores WHERE store_name='맛있는 치킨'),
     2, '양념 치킨', 'CHICKEN', 20000, '매콤달콤한 양념 치킨', TRUE, NULL,
     FALSE, 30,
     now(),'system',now(),'system'),
    (gen_random_uuid(),
     (SELECT store_id FROM p_stores WHERE store_name='맛있는 치킨'),
     3, '간장 치킨', 'CHICKEN', 19000, '구수한 간장 치킨', TRUE, NULL,
     FALSE, 28,
     now(),'system',now(),'system'),
    (gen_random_uuid(),
     (SELECT store_id FROM p_stores WHERE store_name='맛있는 치킨'),
     4, '치킨 버거', 'BURGER', 12000, '치킨 패티가 들어간 버거', TRUE, NULL,
     FALSE, 35,
     now(),'system',now(),'system'),
    (gen_random_uuid(),
     (SELECT store_id FROM p_stores WHERE store_name='맛있는 치킨'),
     5, '치킨 샐러드', 'SALAD', 8000, '치킨이 들어간 샐러드', TRUE, NULL,
     FALSE, 20,
     now(),'system',now(),'system'),
    (gen_random_uuid(),
     (SELECT store_id FROM p_stores WHERE store_name='버거 하우스'),
     1, '치즈버거', 'BURGER', 8000, '치즈가 들어간 기본 버거', TRUE, NULL,
     FALSE, 50,
     now(),'system',now(),'system'),
    (gen_random_uuid(),
     (SELECT store_id FROM p_stores WHERE store_name='버거 하우스'),
     2, '불고기버거', 'BURGER', 9000, '불고기 패티가 들어간 버거', TRUE, NULL,
     FALSE, 45,
     now(),'system',now(),'system'),
    (gen_random_uuid(),
     (SELECT store_id FROM p_stores WHERE store_name='버거 하우스'),
     3, '치킨버거', 'BURGER', 10000, '치킨 패티가 들어간 버거', TRUE, NULL,
     FALSE, 40,
     now(),'system',now(),'system'),
    (gen_random_uuid(),
     (SELECT store_id FROM p_stores WHERE store_name='버거 하우스'),
     4, '감자튀김', 'SIDE', 3000, '바삭한 감자튀김', TRUE, NULL,
     FALSE, 100,
     now(),'system',now(),'system'),
    (gen_random_uuid(),
     (SELECT store_id FROM p_stores WHERE store_name='버거 하우스'),
     5, '콜라', 'DRINK', 2000, '시원한 콜라', TRUE, NULL,
     TRUE, 0,
     now(),'system',now(),'system'),
    (gen_random_uuid(),
     (SELECT store_id FROM p_stores WHERE store_name='스시 마스터'),
     1, '초밥', 'SUSHI', 15000, '신선한 초밥', TRUE, NULL,
     FALSE, 50,
     now(),'system',now(),'system'),
    (gen_random_uuid(),
     (SELECT store_id FROM p_stores WHERE store_name='스시 마스터'),
     2, '회', 'SUSHI', 20000, '신선한 회', TRUE, NULL,
     FALSE, 40,
     now(),'system',now(),'system'),
    (gen_random_uuid(),
     (SELECT store_id FROM p_stores WHERE store_name='스시 마스터'),
     3, '초밥 세트', 'SUSHI_SET', 25000, '초밥과 무침 세트', TRUE, NULL,
     FALSE, 30,
     now(),'system',now(),'system'),
    (gen_random_uuid(),
     (SELECT store_id FROM p_stores WHERE store_name='중국집'),
     1, '짜장면', 'JAJANGMYEON', 8000, '짜장면', TRUE, NULL,
     FALSE, 60,
     now(),'system',now(),'system'),
    (gen_random_uuid(),
     (SELECT store_id FROM p_stores WHERE store_name='중국집'),
     2, '짬뽕', 'JAMBOP', 9000, '짬뽕', TRUE, NULL,
     FALSE, 55,
     now(),'system',now(),'system'),
    (gen_random_uuid(),
     (SELECT store_id FROM p_stores WHERE store_name='중국집'),
     3, '탕수육', 'TANGSUYUK', 15000, '탕수육', TRUE, NULL,
     FALSE, 45,
     now(),'system',now(),'system'),
    (gen_random_uuid(),
     (SELECT store_id FROM p_stores WHERE store_name='중국집'),
     4, '팔보채', 'PALBOOCHA', 12000, '팔보채', TRUE, NULL,
     FALSE, 70,
     now(),'system',now(),'system'),
    (gen_random_uuid(),
     (SELECT store_id FROM p_stores WHERE store_name='중국집'),
     5, '카페라떼', 'COFFEE', 4000, '카페라떼', TRUE, NULL,
     FALSE, 30,
     now(),'system',now(),'system'),
    (gen_random_uuid(),
     (SELECT store_id FROM p_stores WHERE store_name='커피 로스터'),
     1, '아메리카노', 'AMERICANO', 3000, '아메리카노', TRUE, NULL,
     FALSE, 100,
     now(),'system',now(),'system'),
    (gen_random_uuid(),
     (SELECT store_id FROM p_stores WHERE store_name='커피 로스터'),
     2, '카페라떼', 'LATTE', 4000, '카페라떼', TRUE, NULL,
     FALSE, 80,
     now(),'system',now(),'system'),
    (gen_random_uuid(),
     (SELECT store_id FROM p_stores WHERE store_name='커피 로스터'),
     3, '카페모카', 'MOCHA', 5000, '카페모카', TRUE, NULL,
     FALSE, 70,
     now(),'system',now(),'system'),
    (gen_random_uuid(),
     (SELECT store_id FROM p_stores WHERE store_name='커피 로스터'),
     4, '카페라떼 블랙', 'BLACK_LATTE', 4500, '카페라떼 블랙', TRUE, NULL,
     FALSE, 60,
     now(),'system',now(),'system'),
    (gen_random_uuid(),
     (SELECT store_id FROM p_stores WHERE store_name='디저트 카페'),
     1, '아이스크림', 'ICECREAM', 5000, '아이스크림', TRUE, NULL,
     FALSE, 100,
     now(),'system',now(),'system'),
    (gen_random_uuid(),
     (SELECT store_id FROM p_stores WHERE store_name='디저트 카페'),
     2, '초콜릿 케이크', 'CHOCOLATE_CAKE', 12000, '초콜릿 케이크', TRUE, NULL,
     FALSE, 50,
     now(),'system',now(),'system'),
    (gen_random_uuid(),
     (SELECT store_id FROM p_stores WHERE store_name='디저트 카페'),
     3, '피넛 초콜릿', 'PEANUT_CHOCOLATE', 8000, '피넛 초콜릿', TRUE, NULL,
     FALSE, 80,
     now(),'system',now(),'system'),
    (gen_random_uuid(),
     (SELECT store_id FROM p_stores WHERE store_name='디저트 카페'),
     4, '초콜릿 케이크 세트', 'CHOCOLATE_CAKE_SET', 15000, '초콜릿 케이크 세트', TRUE, NULL,
     FALSE, 40,
     now(),'system',now(),'system'),
    (gen_random_uuid(),
     (SELECT store_id FROM p_stores WHERE store_name='고기집'),
     1, '소고기 스테이크', 'STEAK', 25000, '소고기 스테이크', TRUE, NULL,
     FALSE, 30,
     now(),'system',now(),'system'),
    (gen_random_uuid(),
     (SELECT store_id FROM p_stores WHERE store_name='고기집'),
     2, '소고기 소시지', 'SUSHI', 18000, '소고기 소시지', TRUE, NULL,
     FALSE, 40,
     now(),'system',now(),'system'),
    (gen_random_uuid(),
     (SELECT store_id FROM p_stores WHERE store_name='고기집'),
     3, '소고기 파스타', 'PASTA', 15000, '소고기 파스타', TRUE, NULL,
     FALSE, 50,
     now(),'system',now(),'system'),
    (gen_random_uuid(),
     (SELECT store_id FROM p_stores WHERE store_name='고기집'),
     4, '소고기 스테이크 세트', 'STEAK_SET', 30000, '소고기 스테이크 세트', TRUE, NULL,
     FALSE, 25,
     now(),'system',now(),'system'),
    (gen_random_uuid(),
     (SELECT store_id FROM p_stores WHERE store_name='고기집'),
     5, '소고기 소시지 세트', 'SUSHI_SET', 20000, '소고기 소시지 세트', TRUE, NULL,
     FALSE, 35,
     now(),'system',now(),'system');


INSERT INTO delivery_areas (area_id, area_name, created_at, created_by, updated_at, updated_by)
VALUES
    (gen_random_uuid(), '종로구', now(),'system',now(),'system'),
    (gen_random_uuid(), '마포구', now(),'system',now(),'system'),
    (gen_random_uuid(), '강남구', now(),'system',now(),'system'),
    (gen_random_uuid(), '서초구', now(),'system',now(),'system');


INSERT INTO p_store_delivery_areas (
    store_id, area_id, delivery_fee,
    created_at, created_by, updated_at, updated_by
)
VALUES
    ((SELECT store_id FROM p_stores WHERE store_name='길동네 한식당'),
     (SELECT area_id FROM delivery_areas WHERE area_name='종로구'), 2000,
     now(),'system',now(),'system'),
    ((SELECT store_id FROM p_stores WHERE store_name='철수네 분식'),
     (SELECT area_id FROM delivery_areas WHERE area_name='마포구'), 1500,
     now(),'system',now(),'system'),
    ((SELECT store_id FROM p_stores WHERE store_name='마포 양식당'),
     (SELECT area_id FROM delivery_areas WHERE area_name='강남구'), 3000,
     now(),'system',now(),'system'),
    ((SELECT store_id FROM p_stores WHERE store_name='맛있는 치킨'),
     (SELECT area_id FROM delivery_areas WHERE area_name='강남구'), 2500,
     now(),'system',now(),'system'),
    ((SELECT store_id FROM p_stores WHERE store_name='버거 하우스'),
     (SELECT area_id FROM delivery_areas WHERE area_name='서초구'), 2000,
     now(),'system',now(),'system'),
    ((SELECT store_id FROM p_stores WHERE store_name='스시 마스터'),
     (SELECT area_id FROM delivery_areas WHERE area_name='강남구'), 3500,
     now(),'system',now(),'system'),
    ((SELECT store_id FROM p_stores WHERE store_name='중국집'),
     (SELECT area_id FROM delivery_areas WHERE area_name='서초구'), 1800,
     now(),'system',now(),'system'),
    ((SELECT store_id FROM p_stores WHERE store_name='커피 로스터'),
     (SELECT area_id FROM delivery_areas WHERE area_name='마포구'), 2200,
     now(),'system',now(),'system'),
    ((SELECT store_id FROM p_stores WHERE store_name='디저트 카페'),
     (SELECT area_id FROM delivery_areas WHERE area_name='강남구'), 2800,
     now(),'system',now(),'system'),
    ((SELECT store_id FROM p_stores WHERE store_name='고기집'),
     (SELECT area_id FROM delivery_areas WHERE area_name='종로구'), 2500,
     now(),'system',now(),'system');


INSERT INTO p_ai_responses (ai_response_id, description, created_at, created_by, updated_at, updated_by)
VALUES
    (gen_random_uuid(), '메뉴 설명 자동 생성 결과 샘플', now(),'system',now(),'system');


INSERT INTO daily_store_sales (
    sale_date, store_id, order_count, total_amount,
    created_at, created_by, updated_at, updated_by
)
VALUES
    (CURRENT_DATE - INTERVAL '2 days',
     (SELECT store_id FROM p_stores WHERE store_name='길동네 한식당'),
     20, 180000, now(),'system',now(),'system'),
    (CURRENT_DATE - INTERVAL '1 day',
     (SELECT store_id FROM p_stores WHERE store_name='철수네 분식'),
     35, 220000, now(),'system',now(),'system'),
    (CURRENT_DATE,
     (SELECT store_id FROM p_stores WHERE store_name='마포 양식당'),
     10, 150000, now(),'system',now(),'system'),
    (CURRENT_DATE,
     (SELECT store_id FROM p_stores WHERE store_name='맛있는 치킨'),
     15, 270000, now(),'system',now(),'system'),
    (CURRENT_DATE,
     (SELECT store_id FROM p_stores WHERE store_name='버거 하우스'),
     12, 144000, now(),'system',now(),'system'),
    (CURRENT_DATE,
     (SELECT store_id FROM p_stores WHERE store_name='스시 마스터'),
     10, 250000, now(),'system',now(),'system'),
    (CURRENT_DATE,
     (SELECT store_id FROM p_stores WHERE store_name='중국집'),
     10, 120000, now(),'system',now(),'system'),
    (CURRENT_DATE,
     (SELECT store_id FROM p_stores WHERE store_name='커피 로스터'),
     8, 40000, now(),'system',now(),'system'),
    (CURRENT_DATE,
     (SELECT store_id FROM p_stores WHERE store_name='디저트 카페'),
     15, 120000, now(),'system',now(),'system'),
    (CURRENT_DATE,
     (SELECT store_id FROM p_stores WHERE store_name='고기집'),
     10, 250000, now(),'system',now(),'system');

INSERT INTO daily_menu_sales (
    sale_date, store_id, menu_id, quantity_sold, total_amount,
    created_at, created_by, updated_at, updated_by
)
VALUES
    (CURRENT_DATE - INTERVAL '2 days',
     (SELECT store_id FROM p_stores WHERE store_name='길동네 한식당'),
     (SELECT menu_id FROM p_menus WHERE menu_name='비빔밥'),
     15, 135000, now(),'system',now(),'system'),
    (CURRENT_DATE - INTERVAL '1 day',
     (SELECT store_id FROM p_stores WHERE store_name='철수네 분식'),
     (SELECT menu_id FROM p_menus WHERE menu_name='떡볶이'),
     20, 120000, now(),'system',now(),'system'),
    (CURRENT_DATE - INTERVAL '1 day',
     (SELECT store_id FROM p_stores WHERE store_name='철수네 분식'),
     (SELECT menu_id FROM p_menus WHERE menu_name='김밥'),
     15, 60000, now(),'system',now(),'system'),
    (CURRENT_DATE,
     (SELECT store_id FROM p_stores WHERE store_name='마포 양식당'),
     (SELECT menu_id FROM p_menus WHERE menu_name='스파게티'),
     10, 120000, now(),'system',now(),'system'),
    (CURRENT_DATE,
     (SELECT store_id FROM p_stores WHERE store_name='맛있는 치킨'),
     (SELECT menu_id FROM p_menus WHERE menu_name='후라이드 치킨'),
     15, 270000, now(),'system',now(),'system'),
    (CURRENT_DATE,
     (SELECT store_id FROM p_stores WHERE store_name='버거 하우스'),
     (SELECT menu_id FROM p_menus WHERE menu_name='치즈버거'),
     10, 80000, now(),'system',now(),'system'),
    (CURRENT_DATE,
     (SELECT store_id FROM p_stores WHERE store_name='스시 마스터'),
     (SELECT menu_id FROM p_menus WHERE menu_name='초밥'),
     10, 150000, now(),'system',now(),'system'),
    (CURRENT_DATE,
     (SELECT store_id FROM p_stores WHERE store_name='중국집'),
     (SELECT menu_id FROM p_menus WHERE menu_name='짜장면'),
     10, 80000, now(),'system',now(),'system'),
    (CURRENT_DATE,
     (SELECT store_id FROM p_stores WHERE store_name='커피 로스터'),
     (SELECT menu_id FROM p_menus WHERE menu_name='아메리카노'),
     8, 24000, now(),'system',now(),'system'),
    (CURRENT_DATE,
     (SELECT store_id FROM p_stores WHERE store_name='디저트 카페'),
     (SELECT menu_id FROM p_menus WHERE menu_name='아이스크림'),
     15, 75000, now(),'system',now(),'system'),
    (CURRENT_DATE,
     (SELECT store_id FROM p_stores WHERE store_name='고기집'),
     (SELECT menu_id FROM p_menus WHERE menu_name='소고기 스테이크'),
     10, 250000, now(),'system',now(),'system');


INSERT INTO menu_vectors (menu_name, tfidf_vector) VALUES
    ('비빔밥', '{"비빔밥": 1.0}'),
    ('김치찌개', '{"김치찌개": 1.0}'),
    ('불고기', '{"불고기": 1.0}'),
    ('된장찌개', '{"된장찌개": 1.0}'),
    ('제육볶음', '{"제육볶음": 1.0}'),
    ('떡볶이', '{"떡볶이": 1.0}'),
    ('김밥', '{"김밥": 1.0}'),
    ('라면', '{"라면": 1.0}'),
    ('순대', '{"순대": 1.0}'),
    ('튀김', '{"튀김": 1.0}'),
    ('스파게티', '{"스파게티": 1.0}'),
    ('까르보나라', '{"까르보나라": 1.0}'),
    ('스테이크', '{"스테이크": 1.0}'),
    ('피자', '{"피자": 1.0}'),
    ('샐러드', '{"샐러드": 1.0}'),
    ('후라이드 치킨', '{"후라이드": 0.7, "치킨": 0.7}'),
    ('양념 치킨', '{"양념": 0.7, "치킨": 0.7}'),
    ('간장 치킨', '{"간장": 0.7, "치킨": 0.7}'),
    ('치킨 버거', '{"치킨": 0.7, "버거": 0.7}'),
    ('치킨 샐러드', '{"치킨": 0.7, "샐러드": 0.7}'),
    ('치즈버거', '{"치즈": 0.7, "버거": 0.7}'),
    ('불고기버거', '{"불고기": 0.7, "버거": 0.7}'),
    ('치킨버거', '{"치킨": 0.7, "버거": 0.7}'),
    ('감자튀김', '{"감자": 0.7, "튀김": 0.7}'),
    ('콜라', '{"콜라": 1.0}'),
    ('초밥', '{"초밥": 1.0}'),
    ('회', '{"회": 1.0}'),
    ('초밥 세트', '{"초밥": 0.7, "세트": 0.7}'),
    ('짜장면', '{"짜장면": 1.0}'),
    ('짬뽕', '{"짬뽕": 1.0}'),
    ('탕수육', '{"탕수육": 1.0}'),
    ('팔보채', '{"팔보채": 1.0}'),
    ('아메리카노', '{"아메리카노": 1.0}'),
    ('카페라떼', '{"카페라떼": 1.0}'),
    ('카페모카', '{"카페모카": 1.0}'),
    ('카페라떼 블랙', '{"카페라떼": 0.7, "블랙": 0.7}'),
    ('아이스크림', '{"아이스크림": 1.0}'),
    ('초콜릿 케이크', '{"초콜릿": 0.7, "케이크": 0.7}'),
    ('피넛 초콜릿', '{"피넛": 0.7, "초콜릿": 0.7}'),
    ('초콜릿 케이크 세트', '{"초콜릿": 0.5, "케이크": 0.5, "세트": 0.5}'),
    ('소고기 스테이크', '{"소고기": 0.7, "스테이크": 0.7}'),
    ('소고기 소시지', '{"소고기": 0.7, "소시지": 0.7}'),
    ('소고기 파스타', '{"소고기": 0.7, "파스타": 0.7}'),
    ('소고기 스테이크 세트', '{"소고기": 0.5, "스테이크": 0.5, "세트": 0.5}'),
    ('소고기 소시지 세트', '{"소고기": 0.5, "소시지": 0.5, "세트": 0.5}');
